export const GET_MAPT = 'get_mapt';
export const WAITING = 'WAITING';
export const TABS_FETCH_SUCCESS = 'TABS_FETCH_SUCCESS';
export const SELECT_TAB = 'SELECT_TAB';
export const HEART_RATE_CHART_FETCH_SUCCESS = 'HEART_RATE_CHART_FETCH_SUCCESS';
export const ALL_VITAL_SIGNS_FETCHED = 'ALL_VITAL_SIGNS_FETCHED';

